import os
import requests
import time
import replicate

# --- CONFIGURATION ---
# These keys are set in GitHub Settings > Secrets
GUMROAD_TOKEN = os.environ.get("GUMROAD_TOKEN")
REPLICATE_TOKEN = os.environ.get("REPLICATE_TOKEN")
BASE44_API_URL = os.environ.get("BASE44_API_URL") # You need the URL where your AI lives

def get_prompt_from_base44():
    """
    Connects to your Base44 AI to get a creative prompt.
    You must ensure Base44 can be reached via a URL or Webhook.
    """
    print("Connecting to Base44 AI...")
    
    # IF BASE44 SENDS DATA VIA WEBHOOK: 
    # This part is tricky on GitHub Actions. 
    # For this script, we assume Base44 has an endpoint we can PING, 
    # OR we use a backup prompt if Base44 is unreachable for this demo.
    
    try:
        # Attempt to call Base44 (Replace with your actual Base44 endpoint)
        response = requests.get(BASE44_API_URL)
        if response.status_code == 200:
            data = response.json()
            # Assuming Base44 returns JSON like {"prompt": "neon fractal tunnel"}
            return data.get("prompt", "A 3D psychedelic fractal tunnel")
    except Exception as e:
        print(f"Could not reach Base44: {e}")
        
    # FALLBACK PROMPT (Used if Base44 connection fails)
    return "A 3D psychedelic neon fractal tunnel spiraling into infinite darkness, vaporwave style, 8k resolution"

def generate_video(prompt):
    """
    Uses Replicate (Stable Video Diffusion) to generate the video.
    """
    print(f"Generating video for prompt: {prompt}")
    
    client = replicate.Client(api_token=REPLICATE_TOKEN)
    
    # We use Stable Video Diffusion. It requires an image to start.
    # I am using a static abstract image URL as the "seed" for the video.
    input_image = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg"
    
    # You can replace 'input_image' with a URL from Base44 if your AI generates images too.
    
    output = client.run(
        "stability-ai/stable-video-diffusion:3f0457e4619daac51203dedb472816fd4af51f3149fa7a9e0b5ffcf1b8172438",
        input={
            "input_image": input_image,
            "frame_rate": 24,
            "motion_bucket_id": 127 # Higher = more psychedelic movement
        }
    )
    
    # The output is a list containing the video URL
    return output[0]

def post_to_gumroad(video_url, prompt):
    """
    Creates a product on Gumroad via API.
    """
    print("Posting to Gumroad...")
    
    url = "https://api.gumroad.com/v2/products"
    
    headers = {
        "Authorization": f"Bearer {GUMROAD_TOKEN}"
    }
    
    # Clean up the prompt to make a nice title
    title = f"AI Psychedelic Video #{int(time.time())}"
    
    data = {
        "title": title,
        "description": f"Generated by AI. Prompt: {prompt}",
        "price": 10, # Price in cents (10 cents? Change to 500 for $5.00)
        "variants_json": '[{"name":"Default","price":500,"external_id":"default"}]', # Set price to $5 here
        "category": "digital_art",
        "content": [
            {
                "url": video_url, 
                "description": "HD Video File",
                "file_name": "psychedelic_gen.mp4",
                "preview": False
            }
        ]
    }

    response = requests.post(url, headers=headers, data=data)
    
    if response.status_code == 200:
        print("SUCCESS! Product created.")
        print(response.json())
    else:
        print("Error posting to Gumroad:", response.text)

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    # 1. Get Idea from Base44
    prompt = get_prompt_from_base44()
    
    # 2. Generate Video
    video_url = generate_video(prompt)
    
    # 3. Post to Gumroad
    post_to_gumroad(video_url, prompt)
